# Generated by Django 4.1.7 on 2023-03-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_shippingaddress_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer',
            field=models.BooleanField(default=True),
        ),
    ]
